# Generated by Django 4.1.7 on 2023-02-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='bal_amt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='amount',
            name='paid_amt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='std_phnum',
            field=models.IntegerField(unique=True),
        ),
    ]
