# Generated by Django 4.1.7 on 2023-02-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0002_alter_amount_bal_amt_alter_amount_paid_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amount',
            name='reciept_id',
            field=models.IntegerField(unique=True),
        ),
    ]
