# Generated by Django 4.1.7 on 2023-02-24 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0005_remove_amount_bal_amt_remove_amount_paid_amt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept_id', models.IntegerField(unique=True, verbose_name='Reciept ID')),
                ('paid_amount', models.IntegerField(default=0, verbose_name='Amount Paid')),
                ('bal_amount', models.IntegerField(default=0, verbose_name='Balance')),
                ('Pay_date', models.DateTimeField(auto_now=True, verbose_name='Payment')),
                ('fee_month', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stds',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('phone_num', models.IntegerField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='Phone No.')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('hostel', models.CharField(max_length=100, verbose_name='Hostel Name')),
            ],
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.AddField(
            model_name='messfee',
            name='phone_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminportal.stds', verbose_name='Phone No.'),
        ),
    ]
