# Generated by Django 4.1.7 on 2023-02-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0012_alter_student_std_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messfee',
            name='trans_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Transaction ID'),
        ),
    ]
