# Generated by Django 4.1.7 on 2023-02-27 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0014_updates_messmenu_friday_messmenu_saturday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_num',
            field=models.CharField(max_length=112, validators=[django.core.validators.RegexValidator(message='Enter phone number without +91', regex='^\\+?1?\\d{9,10}$')]),
        ),
    ]
