# Generated by Django 4.1.7 on 2023-03-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0020_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messfee',
            name='std_id',
        ),
        migrations.DeleteModel(
            name='MessMenu',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Updates',
        ),
        migrations.DeleteModel(
            name='MessFee',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
