# Generated by Django 4.1.7 on 2023-03-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0024_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messfee',
            name='start_date',
        ),
    ]
