# Generated by Django 4.1.7 on 2023-03-09 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0025_remove_messfee_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessMenu',
        ),
    ]
