# Generated by Django 4.1.7 on 2023-03-09 16:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0026_delete_messmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.TextField(null=True, verbose_name='Monday')),
                ('tuesday', models.TextField(null=True, verbose_name='Tuesday')),
                ('wednesday', models.TextField(null=True, verbose_name='Wednesday')),
                ('thursday', models.TextField(null=True, verbose_name='Thursday')),
                ('friday', models.TextField(null=True, verbose_name='Friday')),
                ('saturday', models.TextField(null=True, verbose_name='Saturday')),
                ('sunday', models.TextField(null=True, verbose_name='Sunday')),
                ('remark', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
