# Generated by Django 4.1.7 on 2023-03-11 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0029_messmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messfee',
            name='end_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='messfee',
            name='fee_month',
            field=models.CharField(max_length=255),
        ),
    ]
