# Generated by Django 4.1.7 on 2023-03-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0030_alter_messfee_end_date_alter_messfee_fee_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('Address', models.CharField(max_length=255, verbose_name='Address')),
                ('Owner_name', models.CharField(max_length=255, verbose_name='owner Name')),
                ('Owner_Phonenum', models.CharField(max_length=15, verbose_name='Phone Num')),
                ('telephone', models.CharField(max_length=20, verbose_name='owner Name')),
                ('Company_email', models.EmailField(max_length=255, verbose_name='Email')),
                ('website', models.CharField(max_length=255, verbose_name='Website')),
            ],
        ),
    ]
