# Generated by Django 4.1.7 on 2023-03-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0031_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(default='logo.jpg', upload_to='logo'),
        ),
    ]
