# Generated by Django 4.1.7 on 2023-03-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0032_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='signature',
            field=models.ImageField(default='signatureDef.png', upload_to='assets', verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(default='logo.jpg', upload_to='assets', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Telephone'),
        ),
    ]
