# Generated by Django 4.1.7 on 2023-03-31 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0033_company_signature_alter_company_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='messfee',
            name='std_id',
        ),
        migrations.DeleteModel(
            name='MessMenu',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Updates',
        ),
        migrations.DeleteModel(
            name='MessFee',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
