# Generated by Django 4.1.7 on 2023-02-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0003_alter_amount_reciept_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='id',
        ),
        migrations.AlterField(
            model_name='amount',
            name='reciept_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
