# Generated by Django 4.1.7 on 2023-02-24 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0004_remove_amount_id_alter_amount_reciept_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amount',
            name='bal_amt',
        ),
        migrations.RemoveField(
            model_name='amount',
            name='paid_amt',
        ),
        migrations.RemoveField(
            model_name='amount',
            name='std_phnum',
        ),
        migrations.RemoveField(
            model_name='students',
            name='std_email',
        ),
        migrations.RemoveField(
            model_name='students',
            name='std_hostel',
        ),
        migrations.RemoveField(
            model_name='students',
            name='std_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='std_phnum',
        ),
        migrations.AddField(
            model_name='amount',
            name='Pay_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Payment'),
        ),
        migrations.AddField(
            model_name='amount',
            name='bal_amount',
            field=models.IntegerField(default=0, verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='amount',
            name='paid_amount',
            field=models.IntegerField(default=0, verbose_name='Amount Paid'),
        ),
        migrations.AddField(
            model_name='amount',
            name='phone_num',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='adminportal.students', verbose_name='Phone No.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(default=1, max_length=255, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='hostel',
            field=models.CharField(default=1, max_length=100, verbose_name='Hostel Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Student Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='phone_num',
            field=models.IntegerField(default=1, max_length=12, unique=True, verbose_name='Phone No.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amount',
            name='reciept_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Reciept ID'),
        ),
    ]
