# Generated by Django 4.1.7 on 2023-02-25 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminportal', '0007_delete_messfee_delete_stds'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('phone_num', models.IntegerField(max_length=12, unique=True, verbose_name='Phone No.')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('hostel', models.CharField(max_length=100, verbose_name='Hostel Name')),
            ],
        ),
        migrations.CreateModel(
            name='MessFee',
            fields=[
                ('reciept_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Reciept ID')),
                ('paid_amount', models.IntegerField(default=0, verbose_name='Amount Paid')),
                ('bal_amount', models.IntegerField(default=0, verbose_name='Balance')),
                ('Pay_date', models.DateTimeField(auto_now=True, verbose_name='Payment')),
                ('fee_month', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('phone_num', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminportal.student', verbose_name='Phone No.')),
            ],
        ),
    ]
