# Generated by Django 4.1.7 on 2023-02-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0009_rename_phone_num_messfee_std_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messfee',
            name='std_id',
        ),
        migrations.DeleteModel(
            name='MessMenu',
        ),
        migrations.DeleteModel(
            name='MessFee',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
