# Generated by Django 4.1.7 on 2023-02-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0011_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Student ID:'),
        ),
    ]
