# Generated by Django 4.1.7 on 2023-02-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0015_alter_student_phone_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messfee',
            name='std_id',
        ),
        migrations.DeleteModel(
            name='MessMenu',
        ),
        migrations.DeleteModel(
            name='Updates',
        ),
        migrations.DeleteModel(
            name='MessFee',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
