# Generated by Django 4.1.7 on 2023-02-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0017_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessFee',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
