# Generated by Django 4.1.7 on 2023-03-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0027_messmenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessMenu',
        ),
    ]
