# Generated by Django 4.1.7 on 2023-03-09 17:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0028_delete_messmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', ckeditor.fields.RichTextField()),
                ('tuesday', ckeditor.fields.RichTextField()),
                ('wednesday', ckeditor.fields.RichTextField()),
                ('thursday', ckeditor.fields.RichTextField()),
                ('friday', ckeditor.fields.RichTextField()),
                ('saturday', ckeditor.fields.RichTextField()),
                ('sunday', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
