# Generated by Django 4.1.7 on 2023-03-31 20:38

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminportal', '0034_delete_company_remove_messfee_std_id_delete_messmenu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('Address', models.CharField(max_length=255, verbose_name='Address')),
                ('Owner_name', models.CharField(max_length=255, verbose_name='owner Name')),
                ('Owner_Phonenum', models.CharField(max_length=15, verbose_name='Phone Num')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Telephone')),
                ('Company_email', models.EmailField(blank=True, max_length=255, verbose_name='Email')),
                ('website', models.CharField(blank=True, max_length=255, verbose_name='Website')),
                ('image', models.ImageField(default='assets/logo.jpg', upload_to='assets', verbose_name='logo')),
                ('signature', models.ImageField(default='assets/signatureDef.png', upload_to='assets', verbose_name='Signature')),
            ],
        ),
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', ckeditor.fields.RichTextField()),
                ('tuesday', ckeditor.fields.RichTextField()),
                ('wednesday', ckeditor.fields.RichTextField()),
                ('thursday', ckeditor.fields.RichTextField()),
                ('friday', ckeditor.fields.RichTextField()),
                ('saturday', ckeditor.fields.RichTextField()),
                ('sunday', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('marks', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Student Name')),
                ('phone_num', models.CharField(max_length=112, validators=[django.core.validators.RegexValidator(message='Enter phone number without +91', regex='^\\+?1?\\d{9,10}$')])),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('hostel', models.CharField(max_length=100, verbose_name='Hostel Name')),
                ('room_no', models.IntegerField(verbose_name='Room No.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessFee',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('reciept_id', models.IntegerField(unique=True, verbose_name='Reciept ID')),
                ('paid_amount', models.IntegerField(default=0, verbose_name='Amount Paid')),
                ('bal_amount', models.IntegerField(default=0, verbose_name='Balance')),
                ('Pay_date', models.DateTimeField(auto_now=True, verbose_name='Payment')),
                ('fee_month', models.CharField(max_length=255)),
                ('end_date', models.CharField(max_length=255)),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminportal.student', verbose_name='Student ID')),
            ],
        ),
    ]
