# Generated by Django 4.1.7 on 2023-04-22 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0036_student_profilepic_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messmenu',
            name='monday',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_num',
            field=models.CharField(max_length=112, unique=True, validators=[django.core.validators.RegexValidator(message='Enter phone number without +91', regex='^\\+?1?\\d{9,10}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='profilepic',
            field=models.ImageField(default='assets/profilepics/default.jpg', upload_to='assets/profilepics', verbose_name='profile'),
        ),
    ]
