# Generated by Django 4.1.7 on 2023-05-30 20:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0037_alter_messmenu_monday_alter_student_phone_num_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='tuesday',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
