# Generated by Django 4.1.7 on 2023-05-31 09:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0038_delete_person_alter_messmenu_tuesday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messmenu',
            name='monday',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='tuesday',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
