# Generated by Django 4.1.7 on 2023-05-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0039_alter_messmenu_monday_alter_messmenu_tuesday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messmenu',
            old_name='friday',
            new_name='Menu',
        ),
        migrations.RemoveField(
            model_name='messmenu',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='messmenu',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='messmenu',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='messmenu',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='messmenu',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='messmenu',
            name='wednesday',
        ),
    ]
