# Generated by Django 4.1.7 on 2023-05-31 11:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0040_rename_friday_messmenu_menu_remove_messmenu_monday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messmenu',
            name='Menu',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
