# Generated by Django 4.1.7 on 2023-05-31 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0041_alter_messmenu_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessMenu',
        ),
    ]
