# Generated by Django 4.1.7 on 2023-05-31 11:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0042_delete_messmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=255)),
                ('Menu', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
