# Generated by Django 4.1.7 on 2023-07-25 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0043_messmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOCapplications',
            fields=[
                ('ApplicationId', models.AutoField(primary_key=True, serialize=False, verbose_name='Application ID')),
                ('Programme', models.CharField(max_length=255, verbose_name='Programme')),
                ('status', models.BooleanField(default=False, max_length=255, verbose_name='Approve')),
                ('std_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminportal.student', verbose_name='Student ID')),
            ],
        ),
        migrations.CreateModel(
            name='leaveRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.CharField(max_length=255, verbose_name='Start Date')),
                ('EndDate', models.CharField(max_length=255, verbose_name='End Date')),
                ('App_date', models.DateTimeField(auto_now=True, verbose_name='Date of Application')),
                ('leaveId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminportal.student', verbose_name='Leave ID')),
            ],
        ),
    ]
