# Generated by Django 4.1.7 on 2023-07-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0044_nocapplications_leaverequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequests',
            name='note',
            field=models.TextField(max_length=500, null=True, verbose_name='Note to staff'),
        ),
    ]
